package com.example.weatherapp.utils

val listOfCity = listOf(
        "Adolfo Gonzales",
        "Adrogué Almirante Brown",
        "Alberti Alberti",
        "Alejandro Korn",
        "América Rivadavia",
        "Arrecifes Arrecifes",
        "Avellaneda	Avellaneda",
        "Ayacucho Ayacucho",
        "Azul",
        "Bahía Blanca",
        "Balcarce",
        "Banfield",
        "Baradero",
        "Batán",
        "Béccar",
        "Bella Vista",
        "Benavídez",
        "Benito Juárez",
        "Berazategui",
        "Bernal",
        "Bolívar",
        "Bosques",
        "Boulogne",
        "Bragado",
        "Brandsen",
        "Burzaco",
        "Campana",
        "Cañuelas",
        "Capilla del Señor",
        "Capitán Sarmiento",
        "Carhué",
        "Carlos Casares",
        "Carlos Spegazzini",
        "Carlos Tejedor",
        "Carmen de Areco",
        "Carmen de Patagones",
        "Casbas",
        "Caseros",
        "Castelar",
        "Castelli",
        "Chacabuco",
        "Claypole",
        "Colón",
        "Comandante Nicanor",
        "Coronel Dorrego",
        "Coronel Pringles",
        "Coronel Suárez",
        "Coronel Vidal",
        "Daireaux",
        "Dock Sud",
        "Dolores",
        "Don Torcuato",
        "Eduardo O'Brien",
        "El Jagüel",
        "El Palomar",
        "Tres de Febrero",
        "El Talar",
        "Ezeiza",
        "Ezpeleta",
        "Francisco Álvarez",
        "Florentino Ameghino",
        "Garín",
        "General Alvear",
        "General Arenales",
        "General Belgrano",
        "General Conesa",
        "General Daniel Cerri",
        "General Guido",
        "General Juan Madariaga",
        "General Las Heras",
        "General Lavalle",
        "General Pacheco",
        "General Pinto",
        "General Rodríguez",
        "General Villegas",
        "Gerli",
        "Glew",
        "González Catán",
        "Gregorio de Laferrere",
        "Guaminí",
        "Guernica",
        "Haedo",
        "Henderson",
        "Hudson",
        "Hurlingham",
        "Ingeniero Budge",
        "Ingeniero Maschwitz",
        "Isidro Casanova4",
        "Ituzaingó",
        "José C. Paz",
        "Junín",
        "La Emilia",
        "La Plata",
        "La Tablada",
        "La Unión",
        "Lanús",
        "Laprida",
        "Las Flores",
        "Lezama",
        "Llavallol",
        "Libertad",
        "Lincoln",
        "Lobería",
        "Lobos",
        "Lomas de Zamora",
        "Lomas del Mirador",
        "Longchamps",
        "Los Polvorines",
        "Los Toldos",
        "Luis Guillón",
        "Magdalena",
        "Maipú",
        "Mar de Ajó",
        "Mar del Plata",
        "Mar del Tuyú",
        "Marcos Paz",
        "Mariano Acosta",
        "Martínez",
        "Médanos",
        "Merlo",
        "Miramar",
        "Monte",
        "Monte Chingolo",
        "Monte Grande",
        "Monte Hermoso",
        "Navarro",
        "Necochea",
        "Nueve de Julio",
        "Olavarría",
        "Paso del Rey",
        "Pehuajó",
        "Pellegrini",
        "Pergamino",
        "Pila",
        "Piran",
        "Pilar",
        "Pinamar",
        "Pontevedra",
        "Presidente Derqui",
        "Puan",
        "Punta Alta",
        "Quilmes",
        "Rafael Calzada",
        "Rafael Castillo",
        "Ramallo",
        "Ramos Mejía",
        "Ranchos",
        "Rauch",
        "Rawson",
        "Remedios de Escalada",
        "Rojas",
        "Roque",
        "Saavedra",
        "Saladillo",
        "Salto",
        "San Andrés de Giles",
        "San Antonio de Areco",
        "San Antonio de Padua",
        "San Cayetano",
        "San Fernando",
        "San Francisco Solano",
        "San Isidro",
        "San Juan Bautista",
        "San Justo",
        "San Martín",
        "San Pedro",
        "San Nicolás de los Arroyos",
        "San Vicente",
        "Santa María",
        "Sarandí",
        "Suipacha",
        "Tandil",
        "Tapalqué",
        "Temperley",
        "Tigre",
        "Tornquist",
        "Treinta de Agosto",
        "Trenque Lauquen",
        "Tres Arroyos",
        "Tres Lomas",
        "Tristán Suárez",
        "Turdera",
        "Valentín Alsina",
        "Vedia",
        "Veinticinco de Mayo",
        "Vicente López",
        "Villa Ballester",
        "General San Martín",
        "Villa Elisa",
        "La Plata",
        "Villa Fiorito2",
        "Lomas de Zamora",
        "Villa Luzuriaga",
        "La Matanza",
        "Villa Madero",
        "La Matanza",
        "Villa Ramallo",
        "Villa Tesei",
        "Wilde",
        "Zárate"
)